code: updating-dataframe-in-pandas
title: Updating DataFrame in Pandas
description: This packages cover various aspects of updating a DataFrame in pandas. Topics covered are adding/removing columns and partially updating columns.
author_name: Manas Garg
author_url: http://www.fuzzysparkle.com